### ISSUE TITLE
Issue with output of Parser.parse()

### ISSUE THREAD

**Issue by qurafa** [ahopk127/eecs2311-tab2xml#12]
**Version:** 0.3.0

**Platform:** macOS Big Sur Version 11.0.1

**Steps to reproduce:**
- Create a new class called 'Test'
- In the 'public static void main(String[] args)' create a new String variable called 'input'
- Assign the name of the input file to 'input'
- Create a new Parser variable called 'p' with the input file as 'input' and the instrument as Instrument.GUITAR
- Create a new String called 'output' and assign it to p.parser()

**Expected:** The variable 'output' is properly assigned to p.parser()

**Actual:** The output of p.parser() could not be assigned to the String 'output'

**Priority:** Low-Since this bug doesn't affect the main purpose of the project, which is to generate a MusicXML equivalent of the tablature, and the bug doesn't stop it from doing that. 

**Severity:** High-This is because the feature is one of the ones listed in the user manual of the project, so it has a high impact of the features of the project

**Screenshot:**
![image](https://user-images.githubusercontent.com/57468292/112333226-c8faf000-8c90-11eb-95f8-1fd6e3bb0463.png)

**Comment by ahopk127** [comment]
That feature is not intended.  You are supposed to insert the text tab as a string (contents of the file), not a file or filepath.  I will clarify that in the documentation.

**Comment by ahopk127** [comment]
The documentation issue has been fixed on my feature branch.  This change is expected to be present in the future version `v0.4.0a2`.

**Comment by ahopk127** [comment]
About the error with the output: you need to put the statement in a try-catch block, that is why it is not working.  This was stated in the original documentation but I also clarified that.
