### ISSUE TITLE
Wrong Input & Output Instrument Name

### ISSUE THREAD

**Issue by tizreal** [ahopk127/eecs2311-tab2xml#13]
Area Path: Input-Text Tab > Instrument  with Output - MusicXML > Instrument
Severity: Medium
Priority: Medium
Assigned to: ahopk127/eecs2311-tab2xml
 
Reported By: Odunfa Temiloluwa
Reported On: 2021-03-24
Reason: Defect

Commit #: 8afe0bedea72e52153f9c9dd15dddb934b35e392
Environment: Windows 10, Eclipse IDE 
Description:
Application shows wrong Instrument type in Output - MusicXML after conversion.
Steps To Reproduce:
1) On the Input - Text Tab, click on either “Load from File” or “Enter a text tab into text area”
2) Click on the Convert button
3) Change Instrument type to Bass
4) Click on the convert button
5) You see wrong conversion type and wrong Instrument type

The first picture shows the instument type as Bass before converting
<img width="625" alt="bassbug" src="https://user-images.githubusercontent.com/68396714/112351354-306c6c00-8ca0-11eb-9aa2-530aa1a95c06.PNG">
The second picture shows the instrument type as guitar after converting meaning the xml file is for another instrument type, not the one selected before conversion
<img width="625" alt="GuitarBug" src="https://user-images.githubusercontent.com/68396714/112351360-31050280-8ca0-11eb-92d4-745412a20326.PNG">
 
Expected Result: On clicking the Convert button, on the Output - MusicXML you should see the correct musicXML file in the text area and appropriate Instrument type.

**Comment by ahopk127** [comment]
This is fixed on my feature branch (`feature-ahopkins-frontend`) and should be included in the next version.
