### ISSUE TITLE
Bug Report - No Tuning Error Handling

### ISSUE THREAD

**Issue by jamesmqle** [ahopk127/eecs2311-tab2xml#15]
### Error Description: 
The converter application does not handle invalid string tuning.

### Priority:
LOW

### Machine/Version:
OS: Windows 10
IDE: IntelliJ version 2020.3.1
Java Version: 15.0.3 

### Steps to Reproduce:
1.	Run the Application
2.	Load the Following File [billiejeanbass.txt](https://github.com/ahopk127/eecs2311-tab2xml/files/6199189/billiejeanbass.txt)
 to the Application or Paste the Following Guitar Tablature Inside the TextBox
```
G|---4---2-4----------|--4---2-4----------|
A|-----4-------4-2-4--|----4-------4-2----|
A|--------------------|----------------4--|
E|--------------------|-------------------| 
```
3.	Press the Convert and Save Button

### Expected Result:
The expected result is that the UI should display an error or warning message that the 2nd string tuning has an A instead of a D.
For example, this window will appear when converting the tablature.
![image](https://user-images.githubusercontent.com/56422075/112353815-7fb39c00-8ca2-11eb-9a5f-d89caa266d22.png)

### Actual Result
The actual result produces a musicXML file with no error or warning message.
This bug is not severe, however, if a user were to have the wrong tuning letter, it would still convert it normally. This will decrease user experience. If the output is undesired due to no tuning error handling, they may not be able to find why the output is wrong especially in cases where they input 100+ lines of tablature with one wrong tuning letter.
![image](https://user-images.githubusercontent.com/56422075/112353596-4418d200-8ca2-11eb-97fe-9b2e273ff476.png)

###

**Comment by amirmohamad-yu** [comment]
The user didn't set the tune of that string to D though. If standard tuning is not set it should be what the user specifies. Can you clarify why its not correct?

**Comment by ahopk127** [comment]
It has been over two weeks since this question was asked and there is no response.  I am closing this issue, it can be reopened if there is a response.
