### ISSUE TITLE
Issue with saving output MusicXML on macOS

### ISSUE THREAD

**Issue by qurafa** [ahopk127/eecs2311-tab2xml#21]
**Version:** 0.3.0

**Platform:** 
macOS Big Sur Version 11.0.1
Eclipse
Java Version 15

**Steps to reproduce:** 
- Open the project on Eclipse
- Open 'Gradle Tasks'
- Expand 'application'
- Double click on 'run' and wait for the application to come up
- Load the tablature you want to convert from file then click 'Convert and Save'
- Then wait for the save pop-up to come up

**Expected:** I expected to be able to name the file and save the MusicXML output to my preferred location

**Actual:** I did not have the option to name the file or save the file to the location of my choice, I am only able to override an an already existing .xml file, but I can't create a new one

**Priority:** High- because it need to be fixed quickly in order to make sure people using the macOS same as other operating systems, are able to use the MusicXML after conversion

**Severity:** High - because it blocks the main purpose of the project, by not letting people save the file after conversion from tablature

**Screenshot:**
![image](https://user-images.githubusercontent.com/57468292/112392109-49d8dc80-8ccf-11eb-969b-4425084bde0d.png)

**Comment by ahopk127** [comment]
Fixed on develop, will be in next version.
