### ISSUE TITLE
Able To Save MusicXML With Empty Text Area

### ISSUE THREAD

**Issue by xzippyzachx** [ahopk127/eecs2311-tab2xml#25]
**Version:** 0.3.0

**Platform:** Windows 10, Eclipse

**Reproduction:** 
1. Go to the Output - MusicXML tab
2. Make sure the text area is empty (No conversion was done)
3. Save to file

**Expected:** I would expect that the muiscxml wouldn't be created since there is nothing in the text area. Maybe don't allow the save button to be clicked if the text area is empty (No conversion was done)

**Actual:** A blank muiscxml file is created which is not useful

**Priority:** Low

**Severity:** low - The software is still usable

**Screenshots:**
![image](https://user-images.githubusercontent.com/33043402/112399301-62032880-8cdc-11eb-9f7a-c936beb4bd42.png)
_Empty text area_

**Comment by ahopk127** [comment]
Fixed in develop, will be included in next version.
