### ISSUE TITLE
Incorrect Error Message for Empty Text Area

### ISSUE THREAD

**Issue by ErikaGrandy** [ahopk127/eecs2311-tab2xml#5]
**Issue Title:** Incorrect Error Message for Empty Text Area.

**Version:** 0.3.0

**Platform:** Windows 10

**Steps to Reproduce:**

- 1. Remove any text from text area

- 2. Press “Convert” Button or “Convert and Save” Button

**Expected:** A user friendly popup message indicating that conversion cannot be completed as the text area is empty. The message should contain no unfamiliar words. 

**Actual:** An error message that states an error occurred during parsing, and index is out of bounds. 
“An error occurred during parsing: Index 0 out of bounds for length 0”. Please see the screenshot.

**Priority:** Low - As this bug does not halt the program or prevent use, it is not a high priority. Before finalizing the project the error message should be modified to be more friendly, by checking if the text area is empty before continuing to attempt parsing. While it may be an easy fix, this can be done later on and focus should be on finishing the project.

**Severity:** Low - Bug does not halt the application and allows the user to continue. It is just confusing for a user as it uses specific language and should not be declared as an error. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/36168874/112022510-c2417100-8b08-11eb-93ec-67a73b2cd194.png)

**Comment by ahopk127** [comment]
Fixed on develop, will be included in next version.
